source "https://rubygems.org"

gem "autoprefixer-rails"
gem "html-proofer"
gem "image_optim"
gem "jekyll"
gem "jekyll-assets"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jemoji"
gem "mini_magick"
gem "sass"
gem "sprockets", "~> 3.7"
gem "uglifier"
gem "jekyll-redirect-from"
gem "kramdown", ">= 2.3.0"
gem "kramdown-parser-gfm"
