version: 2
jobs:
  build:
    working_directory: ~/samtay
    docker:
      - image: futtetennista/hakyll:latest
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
            cd _site && git checkout master
      - restore-cache:
          keys:
            - v1-stack-{{ checksum "samtay-github-io.cabal" }}
            - stack-work-
      - run: stack setup
      - run: stack build
      - save_cache:
          paths:
            - ~/samtay/.stack-work
            - /root/.stack/
          key: v1-stack-work-{{ checksum "samtay-github-io.cabal" }}
      - deploy:
          name: Deploy to samtay.github.io
          command: bash .circleci/deploy.sh
