version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
            cd _site && git checkout master
      - restore-cache:
          keys:
            - stack-{{ checksum “stack.yaml” }}
      - restore-cache:
          keys:
            - stack-{{checksum “stack.yaml”}}-{{checksum “samtay-github-io.cabal”}}
      - run: wget https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
      - run: sudo mkdir /tmp/stack-download
      - run: sudo tar -xzf /tmp/stack.tar.gz -C /tmp/stack-download
      - run: sudo chmod +x /tmp/stack-download/stack-1.7.1-linux-x86_64/stack
      - run: sudo mv /tmp/stack-download/stack-1.7.1-linux-x86_64/stack /usr/bin/stack
      - run: stack setup
      - run: stack build
      - run: stack exec samtay-github-io -- clean
      - run: stack exec samtay-github-io -- build
      - save-cache:
          key: stack-{{ checksum “stack.yaml” }}
          paths:
            - “~/.stack”
      - restore-cache:
          keys: stack-{{checksum “stack.yaml”}}-{{checksum “project.cabal”}}
          paths:
            - “.stack-work”
      - deploy:
          name: Deploy to samtay.github.io
          command: |
            if [ $CIRCLE_BRANCH == 'hakyll' ]; then
              bash .circleci/deploy.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy
