version: 2.0

jobs:
  build:
    working_directory: ~/chalk
    branches:
      only:
        - chalk
    docker:
      - image: circleci/ruby:2.7.0-node
    steps:
      - checkout

      - run:
          name: TODO mk docker image with rsync
          command: |
            sudo apt-get install rsync

      - restore_cache:
          keys:
            - v1-rubygem-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-rubygem-dependencies-
      - run:
          name: ruby deps
          command: |
            bundle --version
            #gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
            bundle update
      - save_cache:
          key: v1-rubygem-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - v1-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v1-yarn-dependencies-
      - run:
          name: js deps
          command: yarn install --modules-folder ./_assets/yarn
      - save_cache:
          key: v1-yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - _assets/yarn

      - run:
          name: build for github
          command: bundle exec jekyll build
      - run:
          name: test
          command: |
            bundle exec htmlproofer ./_site --url-swap "https\://samtay.github.io:" --only-4xx --allow-hash-href --assume-extension --check-opengraph --url-ignore "feed.xml,/tag/.*/,/angel.co/"

      - run:
          name: deploy to github.io
          command: |
            cd ~/chalk
            msg="$(git log -1 --pretty=%B) [ci skip]"
            tmpdir=$(mktemp -d)
            git config --global user.email autodeploy@circleci.com
            git config --global user.name CircleCI
            git clone --single-branch --branch master \
              git@github.com:samtay/samtay.github.io.git \
              $tmpdir
            cd $tmpdir
            git rm -rf .
            git clean -fxd
            cp -r ~/chalk/_site/* .
            if [[ $(git status --porcelain) ]]; then
              git add --all
              git commit --allow-empty -m "$msg"
              git push origin master
            fi

      - run:
          name: build for uw
          command: |
            cd ~/chalk
            sed -i 's/samtay.github.io/www.stat.washington.edu/g' _config.yml
            echo "baseurl: /people/tays" >> _config.yml
            bundle exec jekyll build

      - add_ssh_keys:
          fingerprints:
            - "85:bc:f3:fb:f3:fa:66:43:3a:71:40:7c:32:2f:90:f7"
      - run:
          name: deploy to uw
          command: |
            echo $UW_HOST_KEY >> ~/.ssh/known_hosts
            rsync --delete -avce ssh ~/chalk/_site/ $UW_USER@$UW_HOST:public_html
