version: 2
jobs:
  build:
    working_directory: ~/samtay
    docker:
      - image: futtetennista/hakyll:latest
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - restore-cache:
          keys:
            - stack-work-{{ checksum "samtay-github-io.cabal" }}
            - stack-
      - run:
          name: Resolve dependencies
          command: stack setup
          command: stack build --dependencies-only
      - save_cache:
          name: Cache dependencies
          key: stack-work-{{ checksum "samtay-github-io.cabal" }}
          paths:
            - ~/samtay/.stack-work
            - ~/.stack
            - /root/.stack/
      - run:
          name: Build site
          command: stack build
          command: stack exec site rebuild
      - deploy:
          name: Deploy to samtay.github.io
          command: |
            tmpdir=$(mktemp -d)
            git config --global user.email autodeploy@circleci.com
            git config --global user.name CircleCI
            git clone --single-branch --branch master \
              git@github.com:samtay/samtay.github.io.git \
              $tmpdir

            cd $tmpdir

            git rm -rf .
            git clean -fxd
            cp -r ~/samtay/_site/* .
            if [[ $(git status --porcelain) ]]; then
              git add --all
              git commit -m "Update build (`date '+%F %T %Z'`) [ci skip]"
              git push origin master
            fi
